# Generated by Django 5.0.1 on 2024-03-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
    ]
