# Generated by Django 5.0.1 on 2024-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0003_auto_20240304_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='produto',
            field=models.TextField(default='', max_length=255),
        ),
    ]
