# Generated by Django 5.0.1 on 2024-03-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0004_usuario_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='produto',
            field=models.TextField(default='Sem produto', max_length=255),
        ),
    ]
